refactoring
markpolyak/lab-grader pull request #10
Opened 2020-12-11 18:54 UTC by BorissowT

refactor

2020-12-18 03:46 UTC, markpolyak requested changes
Не понятно, что описывает экземпляр класса. Нужны пояснения, логика не понятна. 

Нет примеров использования созданного класса. 

Код в `main.py` не обновлен и продолжает использовать несуществующие методы из модуля `google_sheets`.

2020-12-18 03:46 UTC, markpolyak commented on google_sheets.py
> +        self.student = student
Для чего информация об одном студенте используется при инициализации класса? 

Класс должен хранить копию гугл-таблицы и позволять работать с ней. В гугл-таблице содержится информация о множестве студентов, а не об одном единственном. Для чего здесь в конструктор передаются сведения о студенте? Дальнейшее использование `self.student` в коде мне не понятно.

2020-12-18 03:46 UTC, markpolyak commented on google_sheets.py
> +    @classmethod
Почему `classmethod`, а не instance method? Нужны пояснения

2020-12-18 03:46 UTC, markpolyak commented on google_sheets.py
> +    def __get_sheet_names(cls) -> list:
Аналогично. Что описывает экземпляр этого класса? 

Если экземпляр класса соответствует какой-то конкретной гугл-таблице, то извлекать информацию из локальной копии этой гугл-таблицы логично на уровне экземплярного метода, а не метода класса.

Если экземпляр класса описывает какую-то другую сущность, то нужны пояснения. Не понятно, как это должно работать.

2020-12-18 03:46 UTC, markpolyak commented on main.py
> +                google_sheets.set_student_lab_status(data, student, lab_id_int, "?! Wrong TASKID!",
Очевидно, что в модуле `google_sheets` больше нет функции `set_student_lab_status`, она переместилась в соответствующий класс. Т.е. весь код в файле `main.py` нерабочий.

2020-12-20 10:14 UTC, BorissowT commented
Изменил сущность.
Убрал информацию о студенте.
Добавил имплементацию в main.py.

1.Указатели типов данных установить не могу, так как не имею возможности запустить код и посмотреть формат получаемых данных. Это должен сделать тестировщик, имеющий доступ к запуску приложения.

2020-12-20 22:42 UTC, markpolyak approved these changes
Код запускается и работает, можно мержить. 

TODO: 
1. дальнейшее тестирование на реальных данных; 
2. перенести эти изменения в PR #11

2021-03-12 16:40 UTC, markpolyak commented
Изменения внесены в ветку [dev1](/markpolyak/lab-grader/tree/dev1), см. 51b3d9f8dbaa0891e34d129fa7119537f1c23d6b

2021-03-12 16:40 UTC, closed without merging